### ISSUE TITLE
Doubt on project structure with Dockerfile

### ISSUE THREAD

**Issue by kavimaluskam** [ALSAD-project/alsad-core#1]
(Not sure if its good to ask here, but anyway)
I am thinking of test the daemon on docker, and i am wondering **if its correct to do as follow:**
- Q1. Create `Dockerfile` and update  `/docker-compose.yml` for every `cmd/${app}` .
- Q2. Setup the Dockerfile in cmd side and execute the golang program in pkg.
- Q3. And also i'd to ask the purpose of maintaining directory `dockerfiles`? Basically for copying?
<img width="360" alt="screen shot 2018-02-01 at 10 14 49 am" src="https://user-images.githubusercontent.com/19992414/35657692-c183a50a-0738-11e8-8043-ef707855b733.png">

**Comment by ben181231** [comment]
Yes. Feel free to add more services in `docker-compose.yml` when they are useful for the project. (if the service is only for your development purpose, you can put it in `docker-compose.override.yml` since it has been gitignored). 

For building a docker image for services written in Golang, my practice is 1) build the executable using [Golang Docker image](https://store.docker.com/images/golang), 2) export the executable to the host machine (most likely your development machine), 3) put the executables in more lightweight image, e.g. [alpine](https://store.docker.com/images/alpine). 

As you can see, each service may have at least 2 dockerfiles. I would prefer put them in `dockerfiles` directory so that they will not mess up in the project root.

For Q2, I think there are some misunderstandings. The code in `pkg` directory is not compiled as an executable. The code should be directly imported to the code in `cmd`.
